permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: redcarpet

# 作者信息
author: 
  name: August Rush
  email: th18435133349@gmail.com
  link: http://bbs.jiandaima.com/
  weibo: http://bbs.jiandaima.com/
  github: http://github.com/jiandaima
  music: http://bbs.jiandaima.com/
  linkedin: http://bbs.jiandaima.com/

# 站点信息
title: August Rush的书架
description: 记录读过的书和感受
url: books.augustrush8.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# 主题设置，自动激活某个标签
active: 读书

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档