permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: Kramdown

# 作者信息
author: 
  name: August Rush
  email: th18435133349@gmail.com
  link: https://books.augustrush8.com/

# 站点信息
title: August Rush的书架
description: 记录读过的书和感受
url: books.augustrush8.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/booksicon.png
favicon: /public/img/booksicon.png

# 主题设置，自动激活某个标签
active: 读书

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
